<h1>Seznam článků</h1>
<table>
    <?php foreach ($blog as $clanek) : ?>
        <tr>
            <td>
                <h2><a href="clanek/<?= $clanek['url']?>"><?= $clanek['titulek'] ?></a></h2>
                <?= $clanek['popisek'] ?>
                <?php if ($admin) : ?>
                    <br />
                    <a href="editor/<?= $clanek['url'] ?>">Editovat</a>
                    <a href="clanek/<?= $clanek['url'] ?>/odstranit">Odstranit</a>
                <?php endif ?>
            </td>
        </tr>
    <?php endforeach?>
</table>