<?php if ($admin) : ?>
    <a class="btn btn-outline-info btn-sm me-2 float-right" href="editor">Přidat článek <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-lg" viewBox="0 0 16 16">
    <path fill-rule="evenodd" d="M8 2a.5.5 0 0 1 .5.5v5h5a.5.5 0 0 1 0 1h-5v5a.5.5 0 0 1-1 0v-5h-5a.5.5 0 0 1 0-1h5v-5A.5.5 0 0 1 8 2"/>
    </svg></a>
<?php endif ?>

<h1 class="mb-5 pb-4 display-4 ">Seznam článků</h1>


<table>
    <?php foreach ($blog as $clanek) : ?>
        <tr>
            <td>
                <h4><a href="clanek/<?= $clanek['url']?>" class="clanek"><?= $clanek['titulek'] ?></a></h4>
                    <div class="px-2 mb-5 mt-1">
                        <?= $clanek['popisek'] ?>
                    </div>
            </td>
            <td>
                <?php if ($admin) : ?>
                    <div >
                        <a class="btn btn-outline-success btn-sm m-1" href="editor/<?= $clanek['url'] ?>"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-fill" viewBox="0 0 16 16">
                        <path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.5.5 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11z"/>
                        </svg></a>

                        <a onclick="return confirm('Opravdu chcete smazat tento článek?')" class="btn btn-outline-danger btn-sm m-1" href="clanek/<?= $clanek['url'] ?>/odstranit" ><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-lg" viewBox="0 0 16 16">
                        <path d="M2.146 2.854a.5.5 0 1 1 .708-.708L8 7.293l5.146-5.147a.5.5 0 0 1 .708.708L8.707 8l5.147 5.146a.5.5 0 0 1-.708.708L8 8.707l-5.146 5.147a.5.5 0 0 1-.708-.708L7.293 8z"/>
                        </svg></a>
                    </div>
                <?php endif ?>
            </td>
        </tr>
    <?php endforeach?>
</table>
