
    <div class="container">
        <div class="row justify-content-center mb-4">
            <div class="text-center">
                <h1 class="mb-4 display-4">Dr. Gregory House</h1>
                <h5 class="">Atestovaný diagnostik se specializací na infekční choroby a nefrologii</h5>
            </div>
        </div>   
    
            <div class="text-center">
                <img src="../obrazky/dr.house.png" alt="Dr. Gregory House" class="img-fluid rounded-pill" />
            </div>
            <div class="text-center">
                <div class="mt-5">
                    <p>V mé ordinaci nenajdete klasického lékaře. Jsem brilantní diagnostik s neortodoxními metodami léčby a nekompromisním přístupem k medicíně. Moje ordinace není pro každého, ale pro ty, kteří jsou ochotni podstoupit mou proceduru, je mé léčení často jedinou nadějí.</p>

                    <p>Mé motto je jednoduché: "Každý lže". Nevěřím na lidskou přímost a spoléhám se spíše na objektivní fakta než na emocionální vazby.</p>

                    <p>Má praktika není běžná. Spolu s mým týmem lékařů se často dostáváme do neobvyklých situací, kdy musíme diagnostikovat vzácné nemoci a nekonvenční stavy. Ale má schopnost překračovat hranice tradiční medicíny a nacházet inovativní léčebné postupy mi vydobyla respekt a obdiv.</p>

                    <p>Můj osobní život je záhadou, a to záměrně. Jsem mistrný v tom, jak si udržet vzdálenost od ostatních lidí. Přesto mě obklopují věrní přátelé a kolegové, kteří se snaží prolomit mé ochranné zdi.</p>

                    <p>Pokud jste připraveni na nekompromisní diagnostiku a léčbu, která se řídí výhradně faktickými důkazy, neváhejte navštívit mou ordinaci. Ale buďte připraveni na to, že vaše schopnosti přežít ve světě Dr. Gregoryho House budou podrobeny zkoušce.</p>
                </div>
            </div>
    
    </div>
