<div  class="border border-4 rounded-3 shadow p-5 ">
    <h1 class="display-5">Editor článků</h1>

    <form action="" method="post">
        <input type="hidden" name="clanky_id" value="<?= $clanek['clanky_id'] ?>"/>
        <label for="">
            Titulek<br/>
            <input class="form-control" type="text" name="titulek" value="<?= $clanek['titulek'] ?>"/>
        </label><br/>
        <label for="">
            URL<br/>
            <input class="form-control" type="text" name="url" value="<?= $clanek['url'] ?>"/>
        </label><br/>
        <label for="">
            Popisek<br/>
            <input class="form-control" type="text" name="popisek" value="<?= $clanek['popisek'] ?>"/>
        </label><br/>
        <label for="">
            Klíčová slova<br/>
            <input class="form-control" type="text" name="klicova_slova" value="<?= $clanek['klicova_slova'] ?>"/>
        </label><br/>
        <label for="obsah"></label><textarea name="obsah" id="obsah" cols="30" rows="10"><?= $clanek['obsah'] ?></textarea>
        <input type="submit" value="Uložit článek">   
    </form>
</div>

<script src="/tinymce/js/tinymce/tinymce.min.js"></script>
<script src="/tinymce/jquery.tinymce.min.js" ></script> 

<script type="text/javascript">
    // Nastavení použité pro TinyMCE 5.7.1
    tinymce.init({

        selector: '#obsah', // Alternativní zápis: `selector: 'textarea[name=obsah]'` nebo pouze `selector: 'textarea'`
        language: 'cs',
        toolbar_mode: 'sliding',

        // Doporučené, vypíná převod české diakritiky na entity, šetří místo v tabulce, chceme text formátovat do html tagů
        entities: '160,nbsp',
        entity_encoding: 'named',

        // Doporučené
        plugins: [
            "advlist autolink lists link image charmap print preview anchor",
            "searchreplace visualblocks code fullscreen",
            "insertdatetime media table contextmenu paste"
        ],

        // Doporučené
        toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
    });
</script>