<h2>Nový pacient</h2>

<form method="post">
            <label>
                Jméno:<br />
                <input type="text" name="jmeno" placeholder="Tomáš"/>
            </label><br />
            <label>
                Příjmení:<br />
                <input type="text" name="prijmeni" placeholder="Novotný" />
            </label><br />
            <label>
                Datum narozeni:<br />
                <input type="date" name="datum_narozeni" />
            </label><br />
            <label>
                Telefonní číslo:<br />
                <input type="text" name="telefonni_cislo" placeholder="+420 741 369 258" />
            </label><br />
            <input type="submit" value="Zapsat pacienta" name="submit"/>
        </form>