<div class="border border-4 rounded-3 shadow p-5" >

    <h1 class="display-5">Přihlášení</h1>


    <form method="post" >
        <div class="mb-3 row mt-5"   >
            <label for="exampleInputEmail1" class="col-sm-2 col-form-label mx-5">Email</label>
            <input type="email" name="email"  class="form-control mx-5" id="exampleInputEmail1" aria-describedby="emailHelp" required="required">
        </div>
        <div class="mb-3 row">
            <label for="exampleInputPassword1" class="col-sm-2 col-form-label mx-5">Heslo</label>
            <input type="password" name="heslo" class="form-control mx-5" id="exampleInputPassword1" required="required">
        </div>
        <div>
            <input type="submit" value="Přihlásit" />
        </div>
        
    </form><br/>

    <div class="centrovany mt-5">
        <p>Pokud ještě nemáte účet</p>
        <p><a class="btn btn-outline-success" href="registrace">Zaregistrujte se</a></p>
    </div>
</div>



