<div class="container border border-4 rounded-3 shadow py-4 px-5">
    <div class="text-right font-weight-light">
        <p ><small><?php echo date("j. m. Y") ?></small>    
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-calendar" viewBox="0 0 16 16">
        <path d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5M1 4v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4z"/>
        </svg></p>
        <a class="btn btn-outline-dark btn-sm" href="profil/odhlasit">Odhlásit</a>
    </div>
    <div class="row">
        <div class="col-12">
            <h2 class="centrovany display-6">Vítejte, <?= $jmeno . " " . $prijmeni?>!</h2>
            <div class="card-body">
                <div class="card-title mb-4">
                    <div class="d-flex justify-content-start">
                        <div class="image-container">
                            <?php if (!$admin) : ?>
                                <img src="../obrazky/pacient.png" id="imgProfile" style="width: 150px; height: 150px" class="img-thumbnail" />
                            <?php else: ?>
                                <img src="../obrazky/doctor.png" id="imgProfile" style="width: 150px; height: 150px" class="img-thumbnail" />
                            <?php endif ?>
                        </div>
                        <div class="userData ml-3">
                            <h2 class="d-block text-uppercase" style="font-size: 1.4rem; font-weight: bold"><?= $jmeno . " " . $prijmeni ?></h2>
                            <h4 class="d-block font-weight-light ">
                                <?php if (!$admin) : ?>
                                    pacient
                                <?php else: ?>
                                    lékař</h4>
                                <?php endif ?>
                        </div>
                        <div class="ml-auto">
                            <input type="button" class="btn btn-primary d-none" id="btnDiscard" value="Discard Changes" />
                        </div>
                    </div>
                </div>
                <div class="my-3">
                    <?php if (!$admin) : ?>
                        <a class="btn btn-outline-success btn-sm me-2" href="blog">Seznam článků</a>
                    <?php else: ?>
                        <a class="btn btn-outline-info btn-sm me-2" href="pacienti" >Pacienti</a>
                        <a class="btn btn-outline-warning btn-sm me-2" href="editor">Přidání článku</a>
                        <a class="btn btn-outline-success btn-sm me-2" href="blog">Seznam článků</a>
                    <?php endif ?>
                </div>                        
                <div class="row">
                    <div class="col-12">
                        <ul class="nav nav-tabs mb-4" id="myTab" role="tablist">
                            <li class="nav-item">
                            <!-- protože odkaz nikam neodkazuje cybí zde href="#" -->
                                <a class="nav-link active text-danger-emphasis" id="basicInfo-tab" data-toggle="tab" role="tab" aria-controls="basicInfo" aria-selected="true">Základní informace</a>
                            </li>
                            <!-- sekci o pojištění ještě není vytvořena
                                <li class="nav-item">
                                <a class="nav-link disabled"  tabindex="-1" id="connectedServices-tab" data-toggle="tab" href="#connectedServices" role="tab" aria-controls="connectedServices" aria-selected="false" aria-disabled="true">Pojištění</a> -->
                            </li>
                        </ul>
                        <div class="tab-content ml-1" id="myTabContent">
                            <div class="tab-pane fade show active" id="basicInfo" role="tabpanel" aria-labelledby="basicInfo-tab">
                                <div class="row">
                                    <div class="col-sm-3 col-md-2 col-5">
                                        <label style="font-weight:bold;">Jméno a příjmení</label>
                                    </div>
                                    <div class="col-md-8 col-6">
                                        <?= $jmeno . " " . $prijmeni ?>
                                    </div>
                                </div>
                                <hr />
                                <div class="row">
                                    <div class="col-sm-3 col-md-2 col-5">
                                        <label style="font-weight:bold;">Datum narození</label>
                                    </div>
                                    <div class="col-md-8 col-6">
                                        <?= $datum_narozeni ?>
                                    </div>
                                </div>
                                <hr />
                                <div class="row">
                                    <div class="col-sm-3 col-md-2 col-5">
                                        <label style="font-weight:bold;">Telefonní číslo</label>
                                    </div>
                                    <div class="col-md-8 col-6">
                                        <?= $telefon ?>
                                    </div>
                                </div>
                                <hr />
                                <div class="row">
                                    <div class="col-sm-3 col-md-2 col-5">
                                        <label style="font-weight:bold;">Email</label>
                                    </div>
                                    <div class="col-md-8 col-6">
                                        <?= $email ?>
                                    </div>
                                </div>
                                <hr />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>